# -*- coding: utf-8 -*-
"""NeuroVision

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IF6-8W2jlLRWHpxy_uvoQE_7gbpgGDXj
"""

import os
import sys
import json
import random
from pathlib import Path
from typing import Tuple, List, Dict, Optional

import numpy as np
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

SEED = 42


def set_seed(seed: int = SEED):
    """Set random seeds for reproducible experiments."""
    random.seed(seed)
    np.random.seed(seed)

    torch.manual_seed(seed)

    if torch.cuda.is_available():
        torch.cuda.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)

    # Reproducibility
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False


set_seed(SEED)

DEVICE = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print(f"Using device: {DEVICE}")

if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name(0)}")

if "google.colab" in sys.modules:
    from google.colab import drive

    drive.mount("/content/drive")
try:
    from tqdm.auto import tqdm
except ImportError:
    !pip install -q tqdm
    from tqdm.auto import tqdm


try:
    import SimpleITK as sitk
except ImportError:
    !pip install -q SimpleITK
    import SimpleITK as sitk


try:
    import skfuzzy as fuzz
except ImportError:
    !pip install -q scikit-fuzzy
    import skfuzzy as fuzz


try:
    import monai

    from monai.transforms import (
        Compose,
        LoadImaged,
        EnsureChannelFirstd,
        ScaleIntensityd,
        CastToTyped,
        RandFlipd,
        RandRotated,
        RandGaussianNoised,
        RandShiftIntensityd,
        RandScaleIntensityd,
        RandAffined,
        RandZoomd,
    )

    from monai.losses import (
        TverskyLoss,
        FocalLoss,
    )

    from monai.metrics import DiceMetric

except ImportError:
    !pip install -q monai

    import monai

    from monai.transforms import (
        Compose,
        LoadImaged,
        EnsureChannelFirstd,
        ScaleIntensityd,
        CastToTyped,
        RandFlipd,
        RandRotated,
        RandGaussianNoised,
        RandShiftIntensityd,
        RandScaleIntensityd,
        RandAffined,
        RandZoomd,
    )

    from monai.losses import (
        TverskyLoss,
        FocalLoss,
    )

    from monai.metrics import DiceMetric

USE_AMP = DEVICE.type == "cuda"

if USE_AMP:
    scaler = torch.amp.GradScaler("cuda")
else:
    scaler = None

print("\nEnvironment ready ✔")
print(f"PyTorch : {torch.__version__}")
print(f"MONAI   : {monai.__version__}")
print(f"Device  : {DEVICE}")
print(f"AMP     : {USE_AMP}")

PROJECT_ROOT = Path("/content/drive/MyDrive/MS_DATA_V2")

DATA_ROOT = PROJECT_ROOT / "DataMSLesion2008"          # ham dataset (zip'ten önceki)
EXTRACTED_DIR = PROJECT_ROOT / "neurovision_data" / "extracted"   # extract edilmiş vakalar
MANIFEST_DIR = PROJECT_ROOT / "neurovision_data" / "processed"    # CSV/JSON manifestler

ARTIFACTS_ROOT   = PROJECT_ROOT / "neurovision_artifacts"
PREPROCESSED_DIR = ARTIFACTS_ROOT / "preprocessed"
FCM_DIR          = ARTIFACTS_ROOT / "fcm_probability_maps"
CHECKPOINT_DIR   = ARTIFACTS_ROOT / "checkpoints"
RESULTS_DIR       = ARTIFACTS_ROOT / "results"
LOGS_DIR          = ARTIFACTS_ROOT / "logs"
VERIFY_DIR        = ARTIFACTS_ROOT / "image_verification"

OUTPUT_DIRS = [
    MANIFEST_DIR,
    ARTIFACTS_ROOT,
    PREPROCESSED_DIR,
    FCM_DIR,
    CHECKPOINT_DIR,
    RESULTS_DIR,
    LOGS_DIR,
    VERIFY_DIR,
]
for directory in OUTPUT_DIRS:
    directory.mkdir(parents=True, exist_ok=True)

if not DATA_ROOT.exists():
    available = "\n".join(f"  - {p.name}" for p in PROJECT_ROOT.iterdir()) if PROJECT_ROOT.exists() else "  (PROJECT_ROOT kendisi de yok)"
    raise FileNotFoundError(
        f"Dataset directory was not found:\n{DATA_ROOT}\n"
        f"PROJECT_ROOT ({PROJECT_ROOT}) içindeki gerçek klasörler:\n{available}\n"
        "Yukarıdaki listeden doğru klasör adını bulup DATA_ROOT tanımını güncelle."
    )

if not EXTRACTED_DIR.exists():
    raise FileNotFoundError(
        f"Extracted dataset directory was not found:\n{EXTRACTED_DIR}\n"
        "Run the extraction step before continuing."
    )

REQUIRED_MODALITIES = ["FLAIR", "T1", "T2"]
GEOMETRY_TOLERANCE = 1e-5

def get_site(case_id: str) -> str:
    """Infer acquisition site from case ID."""
    if case_id.startswith("CHB_train_Case"):
        return "CHB"
    if case_id.startswith("UNC_train_Case"):
        return "UNC"
    return "UNKNOWN"


def find_case_directories(root: Path = EXTRACTED_DIR) -> list[Path]:
    """Find CHB and UNC training case directories."""
    case_dirs = []
    for path in root.iterdir():
        if not path.is_dir():
            continue
        if path.name.startswith("CHB_train_Case") or path.name.startswith("UNC_train_Case"):
            case_dirs.append(path)
    return sorted(case_dirs)


MODALITY_KEYWORDS = {
    "FLAIR": "flair",
    "T1": "_t1",
    "T2": "_t2",
    "LESION_BYCHB": "lesion_bychb",
    "LESION": "lesion",
}

def find_modality_file(case_dir: Path, modality: str) -> Path | None:
    """
    Belirtilen modality için tek, deterministik bir dosya döner.
    Uzantı önceliği: .nhdr > .nii > .nii.gz
    'LESION' aranırken 'LESION_BYCHB' dosyaları otomatik hariç tutulur.
    """
    keyword = MODALITY_KEYWORDS[modality]
    exclude = "bychb" if modality == "LESION" else None

    for ext in [".nhdr", ".nii", ".nii.gz"]:
        files = sorted(case_dir.glob(f"*{ext}"))
        files = [f for f in files if keyword in f.name.lower()]
        if exclude:
            files = [f for f in files if exclude not in f.name.lower()]
        if files:
            return files[0]
    return None


def find_all_modalities(case_dir: Path) -> dict:
    """Bir case için tüm modaliteleri (FLAIR, T1, T2, LESION, LESION_BYCHB) bulur."""
    return {mod: find_modality_file(case_dir, mod) for mod in MODALITY_KEYWORDS}


def read_image(path: Path):
    """Read medical image using SimpleITK. Returns (image, error_message)."""
    try:
        image = sitk.ReadImage(str(path))
        return image, None
    except Exception as exc:
        return None, str(exc)


def load_image_array(path: Path):
    """Read image and also return the NumPy array. Returns (image, array, error)."""
    image, err = read_image(path)
    if image is None:
        return None, None, err
    return image, sitk.GetArrayFromImage(image), None


def image_metadata(image) -> dict:
    """Extract relevant geometry metadata (JSON-safe lists, not tuples)."""
    return {
        "size": [int(x) for x in image.GetSize()],
        "spacing": [float(x) for x in image.GetSpacing()],
        "origin": [float(x) for x in image.GetOrigin()],
        "direction": [float(x) for x in image.GetDirection()],
    }


def tuple_close(a, b, tolerance: float = GEOMETRY_TOLERANCE) -> bool:
    """Compare two numeric tuples/lists within a tolerance."""
    if len(a) != len(b):
        return False
    return all(abs(x - y) <= tolerance for x, y in zip(a, b))


print("Config & utils ready ✔")
print(f"PROJECT_ROOT   : {PROJECT_ROOT}")
print(f"DATA_ROOT      : {DATA_ROOT}")
print(f"EXTRACTED_DIR  : {EXTRACTED_DIR}")
print(f"MANIFEST_DIR   : {MANIFEST_DIR}")
print(f"ARTIFACTS_ROOT : {ARTIFACTS_ROOT}")

#DATASET STATISTICS

print("="*80)
print("NEUROVISION DATASET STATISTICS")
print("="*80)

records = []
skipped = []

case_dirs = find_case_directories(EXTRACTED_DIR)
print(f"Cases found : {len(case_dirs)}")

for case in case_dirs:
    flair_path = find_modality_file(case, "FLAIR")
    lesion_path = find_modality_file(case, "LESION")  # byCHB otomatik hariç

    if flair_path is None or lesion_path is None:
        reason = []
        if flair_path is None:
            reason.append("FLAIR missing")
        if lesion_path is None:
            reason.append("lesion missing")
        skipped.append({"case": case.name, "reason": ", ".join(reason)})
        continue

    flair, flair_np, err = load_image_array(flair_path)
    if err:
        skipped.append({"case": case.name, "reason": f"FLAIR read error: {err}"})
        continue

    lesion, lesion_np, err = load_image_array(lesion_path)
    if err:
        skipped.append({"case": case.name, "reason": f"lesion read error: {err}"})
        continue

    flair_np = flair_np.astype(np.float32)

    spacing = flair.GetSpacing()
    origin = flair.GetOrigin()
    direction = flair.GetDirection()

    voxel_volume_mm3 = spacing[0] * spacing[1] * spacing[2]
    lesion_voxels = int(np.sum(lesion_np > 0))
    lesion_volume_mm3 = lesion_voxels * voxel_volume_mm3
    lesion_volume_ml = lesion_volume_mm3 / 1000

    records.append({
        "case": case.name,
        "site": get_site(case.name),
        "shape_z": flair_np.shape[0],
        "shape_y": flair_np.shape[1],
        "shape_x": flair_np.shape[2],
        "spacing_x": spacing[0],
        "spacing_y": spacing[1],
        "spacing_z": spacing[2],
        "origin_x": origin[0],
        "origin_y": origin[1],
        "origin_z": origin[2],
        "direction": str(direction),
        "min": float(flair_np.min()),
        "max": float(flair_np.max()),
        "mean": float(flair_np.mean()),
        "std": float(flair_np.std()),
        "lesion_voxels": lesion_voxels,
        "lesion_volume_mm3": lesion_volume_mm3,
        "lesion_volume_ml": lesion_volume_ml
    })

print()
print("="*80)
print(f"SKIPPED CASES: {len(skipped)}")
print("="*80)
if skipped:
    for s in skipped:
        print(f"  - {s['case']}: {s['reason']}")
else:
    print("  (none)")

stats_df = pd.DataFrame(records)
stats_csv = MANIFEST_DIR / "dataset_statistics.csv"
stats_df.to_csv(stats_csv, index=False)

print()
print("="*80)
print("SUMMARY")
print("="*80)
print(f"Cases found        : {len(case_dirs)}")
print(f"Cases processed    : {len(stats_df)}")
print(f"Cases skipped      : {len(skipped)}")

if len(stats_df) > 0:
    print()
    print("Cases per site")
    print(stats_df["site"].value_counts())

    print()
    print("Image size")
    print(stats_df[["shape_x", "shape_y", "shape_z"]].describe())

    print()
    print("Spacing")
    print(stats_df[["spacing_x", "spacing_y", "spacing_z"]].describe())

    print()
    print("Intensity")
    print(stats_df[["min", "max", "mean", "std"]].describe())

    print()
    print("Lesion Volume (overall)")
    print(stats_df[["lesion_voxels", "lesion_volume_mm3", "lesion_volume_ml"]].describe())

    print()
    print("Lesion Volume (by site)")
    print(stats_df.groupby("site")[["lesion_voxels", "lesion_volume_mm3", "lesion_volume_ml"]].describe())

print()
print("="*80)
print(f"CSV saved -> {stats_csv}")
print("="*80)

display(stats_df.head())

# INTENSITY PREPROCESSING

print("=" * 80)
print("NEUROVISION INTENSITY PREPROCESSING")
print("Percentile Clipping (0.5 - 99.5)")
print("=" * 80)

CLIPPED_DIR = PREPROCESSED_DIR / "clipped"
CLIPPED_DIR.mkdir(parents=True, exist_ok=True)

modalities = ["FLAIR", "T1", "T2"]
records = []

cases = find_case_directories(EXTRACTED_DIR)
print(f"Cases found : {len(cases)}")

for case in cases:
    print(f"\nProcessing {case.name}")
    case_out = CLIPPED_DIR / case.name
    case_out.mkdir(exist_ok=True)

    for modality in modalities:
        image_path = find_modality_file(case, modality)
        if image_path is None:
            print(f"   {modality:<6} missing")
            continue

        image, array, err = load_image_array(image_path)
        if err:
            print(f"   {modality:<6} read error")
            continue

        array = array.astype(np.float32)

        brain_mask = array > 0
        brain = array[brain_mask]

        if brain.size == 0:
            print(f"   {modality:<6} empty")
            continue

        low = np.percentile(brain, 0.5)
        high = np.percentile(brain, 99.5)

        assert low < high, (
            f"{case.name}/{modality}: low={low} >= high={high}, "
            "percentile hesabı bozuk (brain neredeyse sabit değerli olabilir)"
        )

        clipped = array.copy()
        clipped[brain_mask] = np.clip(array[brain_mask], low, high)

        clipped_voxels = int(
            np.sum(brain_mask & ((array < low) | (array > high)))
        )

        background_mask = array <= 0
        assert clipped[background_mask].max() == 0 and clipped[background_mask].min() == 0, (
            f"{case.name}/{modality}: background bozuldu, "
            "clip background'a sızmış olabilir"
        )
        assert clipped[brain_mask].max() <= array[brain_mask].max(), (
            f"{case.name}/{modality}: clip sonrası max büyüdü, mantık hatası var"
        )
        assert clipped[brain_mask].min() >= array[brain_mask].min(), (
            f"{case.name}/{modality}: clip sonrası min küçüldü, mantık hatası var"
        )

        clipped_image = sitk.GetImageFromArray(clipped)
        clipped_image.CopyInformation(image)

        out_path = case_out / f"{case.name}_{modality}_clipped.nii.gz"
        sitk.WriteImage(clipped_image, str(out_path))

        records.append({
            "case": case.name,
            "site": get_site(case.name),
            "modality": modality,
            "low_percentile": float(low),
            "high_percentile": float(high),
            "before_min": float(array.min()),
            "before_max": float(array.max()),
            "after_min": float(clipped.min()),
            "after_max": float(clipped.max()),
            "clipped_voxels": clipped_voxels,
            "brain_voxels": int(brain_mask.sum()),
        })

        print(
            f"   {modality:<6}"
            f" low={low:8.2f}"
            f" high={high:8.2f}"
            f" clipped={clipped_voxels:8d}"
            f" (brain_voxels={int(brain_mask.sum())})"
        )

print()
clip_df = pd.DataFrame(records)
clip_csv = MANIFEST_DIR / "percentile_clipping_statistics.csv"
clip_df.to_csv(clip_csv, index=False)

print("=" * 80)
print("SUMMARY")
print("=" * 80)
print(f"Images processed : {len(clip_df)}")
print()
display(clip_df.head())
print()
print(f"Statistics saved -> {clip_csv}")
print("=" * 80)

# VISUAL QC

def visualize_case(case_dir, raw_case_dir=None):
    """FLAIR / T1 / T2 / lesion overlay / histogram üretir ve PNG olarak kaydeder.

    case_dir     : CLIPPED_DIR altındaki case klasörü (clip edilmiş görüntüler)
    raw_case_dir : EXTRACTED_DIR altındaki aynı case klasörü (ham veri, karşılaştırma için)
    """

    flair_path = find_modality_file(case_dir, "FLAIR")
    t1_path = find_modality_file(case_dir, "T1")
    t2_path = find_modality_file(case_dir, "T2")
    lesion_path = find_modality_file(case_dir, "LESION")

    # Lesion mask'i clip edilmemiş olabilir; CLIPPED_DIR'da bulunamazsa
    # ham veri klasöründen (EXTRACTED_DIR) fallback olarak dene
    if lesion_path is None and raw_case_dir is not None:
        lesion_path = find_modality_file(raw_case_dir, "LESION")

    missing = [
        name for name, p in
        [("FLAIR", flair_path), ("T1", t1_path), ("T2", t2_path), ("LESION", lesion_path)]
        if p is None
    ]
    if missing:
        print(f"  ⚠ SKIPPED {case_dir.name} - missing: {', '.join(missing)}")
        return

    _, flair, err1 = load_image_array(flair_path)
    _, t1, err2 = load_image_array(t1_path)
    _, t2, err3 = load_image_array(t2_path)
    _, lesion, err4 = load_image_array(lesion_path)

    errors = [e for e in [err1, err2, err3, err4] if e]
    if errors:
        print(f"  ⚠ SKIPPED {case_dir.name} - read error: {errors[0]}")
        return

    # Shape uyuşmazlığı varsa overlay hizasız çıkar; erken uyar
    shapes = {"FLAIR": flair.shape, "T1": t1.shape, "T2": t2.shape, "LESION": lesion.shape}
    if len(set(shapes.values())) > 1:
        print(f"  ⚠ SHAPE MISMATCH {case_dir.name}: {shapes}")

    middle = flair.shape[0] // 2

    fig, ax = plt.subplots(2, 3, figsize=(16, 10))

    ax[0, 0].imshow(flair[middle], cmap="gray")
    ax[0, 0].set_title("FLAIR (clipped)")

    ax[0, 1].imshow(t1[middle], cmap="gray")
    ax[0, 1].set_title("T1 (clipped)")

    ax[0, 2].imshow(t2[middle], cmap="gray")
    ax[0, 2].set_title("T2 (clipped)")

    ax[1, 0].imshow(flair[middle], cmap="gray")
    ax[1, 0].imshow(lesion[middle], alpha=0.45, cmap="Reds")
    ax[1, 0].set_title("Mask Overlay")

    ax[1, 1].hist(flair.flatten(), bins=100)
    ax[1, 1].set_title("FLAIR Histogram (clipped)")

    # Ham veriyle karşılaştırma: raw_case_dir verilmişse clip öncesi/sonrası
    # FLAIR histogramlarını üst üste bindir
    if raw_case_dir is not None:
        raw_flair_path = find_modality_file(raw_case_dir, "FLAIR")
        if raw_flair_path is not None:
            _, raw_flair, raw_err = load_image_array(raw_flair_path)
            if not raw_err:
                ax[1, 2].hist(raw_flair.flatten(), bins=100, alpha=0.6, label="raw")
                ax[1, 2].hist(flair.flatten(), bins=100, alpha=0.6, label="clipped")
                ax[1, 2].set_title("FLAIR: Raw vs Clipped")
                ax[1, 2].legend()
            else:
                ax[1, 2].axis("off")
        else:
            ax[1, 2].axis("off")
    else:
        ax[1, 2].axis("off")

    plt.tight_layout()
    out = VERIFY_DIR / f"{case_dir.name}.png"
    plt.savefig(out, dpi=150)
    plt.show()
    print(f"  ✓ saved -> {out}")


# CLIPPED_DIR üzerinden QC yapıyoruz (ham veri değil, clip edilmiş sonuçlar)
cases = find_case_directories(CLIPPED_DIR)
print(f"Total cases: {len(cases)}")

for case in cases:
    print("=" * 60)
    print(case.name)
    raw_case_dir = EXTRACTED_DIR / case.name
    visualize_case(case, raw_case_dir=raw_case_dir if raw_case_dir.exists() else None)

# GEOMETRY STANDARDIZATION + VERIFICATION

TARGET_SPACING = (1.0, 1.0, 1.0)
TARGET_ORIENTATION = "LPS"
IMAGE_INTERPOLATOR = sitk.sitkBSpline
MASK_INTERPOLATOR = sitk.sitkNearestNeighbor

GEOMETRY_DIR = PREPROCESSED_DIR / "geometry_standardized"
GEOMETRY_DIR.mkdir(parents=True, exist_ok=True)

print("=" * 80)
print("NEUROVISION GEOMETRY STANDARDIZATION")
print(f"Target spacing     : {TARGET_SPACING}")
print(f"Target orientation : {TARGET_ORIENTATION}")
print(f"Image interpolator : BSpline (clamp >= 0 sonrasında)")
print(f"Mask interpolator  : NearestNeighbor + binarize")
print("=" * 80)


def get_orientation_code(image) -> str:
    """Görüntünün mevcut yönelim kodunu (LPI, RAI, ...) direction matrix'ten çıkarır."""
    try:
        return sitk.DICOMOrientImageFilter_GetOrientationFromDirectionCosines(
            image.GetDirection()
        )
    except Exception:
        return "UNKNOWN"


def reorient_image(image, orientation: str = TARGET_ORIENTATION):
    """Görüntüyü hedef koordinat yönelimine (LPS) çevirir."""
    orient_filter = sitk.DICOMOrientImageFilter()
    orient_filter.SetDesiredCoordinateOrientation(orientation)
    return orient_filter.Execute(image)


def resample_to_spacing(image, target_spacing=TARGET_SPACING, is_mask: bool = False):
    """Görüntüyü kendi grid'i üzerinde hedef spacing'e resample eder.
    Sadece referans (FLAIR) için kullanılır."""
    original_spacing = image.GetSpacing()
    original_size = image.GetSize()

    new_size = [
        max(1, int(round(osz * ospc / tspc)))
        for osz, ospc, tspc in zip(original_size, original_spacing, target_spacing)
    ]

    resampler = sitk.ResampleImageFilter()
    resampler.SetOutputSpacing(target_spacing)
    resampler.SetSize(new_size)
    resampler.SetOutputDirection(image.GetDirection())
    resampler.SetOutputOrigin(image.GetOrigin())
    resampler.SetTransform(sitk.Transform(3, sitk.sitkIdentity))
    resampler.SetDefaultPixelValue(0)
    resampler.SetInterpolator(MASK_INTERPOLATOR if is_mask else IMAGE_INTERPOLATOR)

    result = resampler.Execute(image)
    return _postprocess(result, is_mask)


def resample_to_reference(image, reference, is_mask: bool = False):
    """Görüntüyü verilen referans grid'e (standardize edilmiş FLAIR) hizalar.
    T1 / T2 / LESION için kullanılır -> tüm modaliteler birebir aynı grid'e oturur."""
    resampler = sitk.ResampleImageFilter()
    resampler.SetReferenceImage(reference)
    resampler.SetTransform(sitk.Transform(3, sitk.sitkIdentity))
    resampler.SetDefaultPixelValue(0)
    resampler.SetInterpolator(MASK_INTERPOLATOR if is_mask else IMAGE_INTERPOLATOR)

    result = resampler.Execute(image)
    return _postprocess(result, is_mask)


def _postprocess(image, is_mask: bool):
    """BSpline overshoot / mask encoding temizliği."""
    if is_mask:
        # Nearest neighbor label değerlerini korur ama farklı encoding'lere
        # (0/1, 0/255, vb.) karşı garanti olsun diye açıkça binarize ediyoruz.
        array = sitk.GetArrayFromImage(image)
        binary = (array > 0).astype(np.uint8)
        out = sitk.GetImageFromArray(binary)
        out.CopyInformation(image)
        return out
    else:
        # BSpline negatif overshoot üretebilir; MRI intensity fiziksel olarak >= 0.
        return sitk.Clamp(image, lowerBound=0.0)


GEOMETRY_MODALITIES = {
    "FLAIR": False,
    "T1": False,
    "T2": False,
    "LESION": True,
}

geometry_records = []
geometry_skipped = []

cases = find_case_directories(EXTRACTED_DIR)
print(f"Cases found : {len(cases)}")

for case in tqdm(cases, desc="Geometry standardization"):

    mod_paths = {mod: find_modality_file(case, mod) for mod in GEOMETRY_MODALITIES}
    missing = [mod for mod, p in mod_paths.items() if p is None]
    if missing:
        geometry_skipped.append({
            "case": case.name,
            "reason": f"missing modalities: {', '.join(missing)}"
        })
        continue

    mod_images = {}
    read_error = None
    for mod, path in mod_paths.items():
        image, err = read_image(path)
        if image is None:
            read_error = f"{mod} read error: {err}"
            break
        mod_images[mod] = image

    if read_error:
        geometry_skipped.append({"case": case.name, "reason": read_error})
        continue

    case_out = GEOMETRY_DIR / case.name
    case_out.mkdir(exist_ok=True)

    # FLAIR referans grid'i oluştur
    flair_image = mod_images["FLAIR"]
    before_orientation = get_orientation_code(flair_image)
    before_meta = image_metadata(flair_image)

    flair_reoriented = reorient_image(flair_image)
    flair_standardized = resample_to_spacing(flair_reoriented, is_mask=False)

    after_meta = image_metadata(flair_standardized)

    sitk.WriteImage(flair_standardized, str(case_out / f"{case.name}_FLAIR_geom.nii.gz"))

    geometry_records.append({
        "case": case.name,
        "site": get_site(case.name),
        "modality": "FLAIR",
        "is_reference": True,
        "before_orientation": before_orientation,
        "after_orientation": TARGET_ORIENTATION,
        "orientation_changed": before_orientation != TARGET_ORIENTATION,
        "before_size": before_meta["size"],
        "after_size": after_meta["size"],
        "before_spacing": before_meta["spacing"],
        "after_spacing": after_meta["spacing"],
        "spacing_changed": not tuple_close(before_meta["spacing"], after_meta["spacing"]),
        "before_origin": before_meta["origin"],
        "after_origin": after_meta["origin"],
    })

    #  T1 / T2 / LESION'ı FLAIR grid'ine hizala
    for modality, is_mask in GEOMETRY_MODALITIES.items():
        if modality == "FLAIR":
            continue

        mod_image = mod_images[modality]
        before_orientation = get_orientation_code(mod_image)
        before_meta = image_metadata(mod_image)

        mod_reoriented = reorient_image(mod_image)
        mod_standardized = resample_to_reference(mod_reoriented, flair_standardized, is_mask=is_mask)

        assert mod_standardized.GetSize() == flair_standardized.GetSize(), (
            f"{case.name}/{modality}: size mismatch after alignment"
        )
        assert tuple_close(mod_standardized.GetSpacing(), flair_standardized.GetSpacing()), (
            f"{case.name}/{modality}: spacing mismatch after alignment"
        )
        assert tuple_close(mod_standardized.GetOrigin(), flair_standardized.GetOrigin()), (
            f"{case.name}/{modality}: origin mismatch after alignment"
        )
        assert tuple_close(mod_standardized.GetDirection(), flair_standardized.GetDirection()), (
            f"{case.name}/{modality}: direction mismatch after alignment"
        )
        if is_mask:
            mask_array = sitk.GetArrayFromImage(mod_standardized)
            assert set(np.unique(mask_array)).issubset({0, 1}), (
                f"{case.name}/{modality}: mask binarize sonrası hala binary değil"
            )

        after_meta = image_metadata(mod_standardized)

        sitk.WriteImage(
            mod_standardized, str(case_out / f"{case.name}_{modality}_geom.nii.gz")
        )

        geometry_records.append({
            "case": case.name,
            "site": get_site(case.name),
            "modality": modality,
            "is_reference": False,
            "before_orientation": before_orientation,
            "after_orientation": TARGET_ORIENTATION,
            "orientation_changed": before_orientation != TARGET_ORIENTATION,
            "before_size": before_meta["size"],
            "after_size": after_meta["size"],
            "before_spacing": before_meta["spacing"],
            "after_spacing": after_meta["spacing"],
            "spacing_changed": not tuple_close(before_meta["spacing"], after_meta["spacing"]),
            "before_origin": before_meta["origin"],
            "after_origin": after_meta["origin"],
        })

print()
print("=" * 80)
print(f"SKIPPED CASES: {len(geometry_skipped)}")
print("=" * 80)
if geometry_skipped:
    for s in geometry_skipped:
        print(f"  - {s['case']}: {s['reason']}")
else:
    print("  (none)")

geometry_df = pd.DataFrame(geometry_records)
geometry_csv = MANIFEST_DIR / "geometry_standardization_statistics.csv"
geometry_df.to_csv(geometry_csv, index=False)

print()
print("=" * 80)
print("SUMMARY")
print("=" * 80)
n_cases_ok = geometry_df["case"].nunique() if len(geometry_df) else 0
print(f"Cases found      : {len(cases)}")
print(f"Cases processed  : {n_cases_ok}")
print(f"Cases skipped    : {len(geometry_skipped)}")
print(f"Statistics saved -> {geometry_csv}")
print("=" * 80)
display(geometry_df.head(10))

# ============================================================
# GEOMETRY QUALITY CONTROL (Overlay Visualization)
# ============================================================

N_CASES = 3

case_dirs = sorted([d for d in GEOMETRY_DIR.iterdir() if d.is_dir()])

random.seed(42)
selected_cases = random.sample(case_dirs, min(N_CASES, len(case_dirs)))

print("=" * 80)
print("GEOMETRY QUALITY CONTROL")
print("=" * 80)

for case_dir in selected_cases:

    case = case_dir.name

    flair = sitk.GetArrayFromImage(
        sitk.ReadImage(str(case_dir / f"{case}_FLAIR_geom.nii.gz"))
    )

    t1 = sitk.GetArrayFromImage(
        sitk.ReadImage(str(case_dir / f"{case}_T1_geom.nii.gz"))
    )

    t2 = sitk.GetArrayFromImage(
        sitk.ReadImage(str(case_dir / f"{case}_T2_geom.nii.gz"))
    )

    lesion = sitk.GetArrayFromImage(
        sitk.ReadImage(str(case_dir / f"{case}_LESION_geom.nii.gz"))
    )

    # Lezyon varsa orta dilim yerine lezyonun en yoğun olduğu dilimi seç
    lesion_sum = lesion.sum(axis=(1, 2))

    if lesion_sum.max() > 0:
        slice_idx = np.argmax(lesion_sum)
    else:
        slice_idx = flair.shape[0] // 2

    fig, ax = plt.subplots(1, 4, figsize=(20, 5))

    # FLAIR
    ax[0].imshow(flair[slice_idx], cmap="gray")
    ax[0].set_title("FLAIR")
    ax[0].axis("off")

    # T1
    ax[1].imshow(t1[slice_idx], cmap="gray")
    ax[1].set_title("T1")
    ax[1].axis("off")

    # T2
    ax[2].imshow(t2[slice_idx], cmap="gray")
    ax[2].set_title("T2")
    ax[2].axis("off")

    # Overlay
    ax[3].imshow(flair[slice_idx], cmap="gray")

    mask = np.ma.masked_where(
        lesion[slice_idx] == 0,
        lesion[slice_idx]
    )

    ax[3].imshow(mask, cmap="autumn", alpha=0.6)

    ax[3].set_title("FLAIR + LESION")
    ax[3].axis("off")

    plt.suptitle(case, fontsize=14)

    plt.tight_layout()

    plt.show()

    print(f"Case      : {case}")
    print(f"Shape     : {flair.shape}")
    print(f"Slice     : {slice_idx}")
    print(f"Lesion voxels in slice : {int(lesion_sum[slice_idx])}")
    print("-" * 80)

# N4 BIAS FIELD CORRECTION

N4_MODALITIES = ["FLAIR", "T1", "T2"]

N4_DIR = PREPROCESSED_DIR / "n4_bias_corrected"
N4_DIR.mkdir(parents=True, exist_ok=True)

BIAS_FIELD_DIR = PREPROCESSED_DIR / "n4_bias_fields"
BIAS_FIELD_DIR.mkdir(parents=True, exist_ok=True)

N4_MASK_DIR = PREPROCESSED_DIR / "n4_otsu_masks"
N4_MASK_DIR.mkdir(parents=True, exist_ok=True)

N4_SHRINK_FACTOR = 4
N4_MAX_ITERATIONS = [50, 50, 50, 50]   # multi-resolution: her seviyede 50 iterasyon
N4_CONVERGENCE_THRESHOLD = 0.001

print("=" * 80)
print("NEUROVISION N4 BIAS FIELD CORRECTION")
print(f"Input          : {GEOMETRY_DIR}")
print(f"Shrink factor  : {N4_SHRINK_FACTOR}")
print(f"Max iterations : {N4_MAX_ITERATIONS}")
print("=" * 80)


def build_brain_mask(image):
    """Otsu eşiklemesiyle beyin/kafa maskesi üretir (arka plan = 0 varsayımıyla).

    N4, bias field'i sadece maske içindeki dokudan tahmin eder; maskenin
    dışındaki (arka plan) voksellerin etkisi tamamen elenir.

    NOT: Bu, N4'ün kendi iç hesabı için kullandığı HAM/hızlı bir Otsu
    maskesidir. Segmentasyon/FCM gibi sonraki adımlar için daha güvenilir,
    delik doldurulmuş bir maske bir sonraki hücrede (ROBUST BRAIN MASK)
    ayrıca üretiliyor.
    """
    mask = sitk.OtsuThreshold(image, 0, 1, 200)
    return mask


def run_n4_correction(image):
    """Görüntüyü N4BiasFieldCorrectionImageFilter ile düzeltir.

    Hız için: (1) görüntü ve maske shrink edilir, (2) log-bias-field bu
    küçültülmüş grid üzerinde kestirilir, (3) bias field orijinal
    çözünürlükte yeniden hesaplanıp tam görüntüye uygulanır.
    """
    image_f32 = sitk.Cast(image, sitk.sitkFloat32)
    mask = build_brain_mask(image_f32)

    if N4_SHRINK_FACTOR > 1:
        image_shrunk = sitk.Shrink(image_f32, [N4_SHRINK_FACTOR] * image_f32.GetDimension())
        mask_shrunk = sitk.Shrink(mask, [N4_SHRINK_FACTOR] * mask.GetDimension())
    else:
        image_shrunk = image_f32
        mask_shrunk = mask

    corrector = sitk.N4BiasFieldCorrectionImageFilter()
    corrector.SetMaximumNumberOfIterations(N4_MAX_ITERATIONS)
    corrector.SetConvergenceThreshold(N4_CONVERGENCE_THRESHOLD)

    _ = corrector.Execute(image_shrunk, mask_shrunk)

    log_bias_field_full = corrector.GetLogBiasFieldAsImage(image_f32)
    bias_field_full = sitk.Exp(log_bias_field_full)
    corrected_full = image_f32 / bias_field_full

    corrected_full = sitk.Clamp(corrected_full, lowerBound=0.0)

    bias_field_full.CopyInformation(image_f32)
    mask.CopyInformation(image_f32)

    return corrected_full, mask, bias_field_full


n4_records = []
n4_skipped = []

cases = find_case_directories(EXTRACTED_DIR)
print(f"Cases found : {len(cases)}")

for case in tqdm(cases, desc="N4 bias field correction"):
    geom_case_dir = GEOMETRY_DIR / case.name
    if not geom_case_dir.exists():
        n4_skipped.append({"case": case.name, "reason": "geometry_standardized klasörü yok"})
        continue

    case_out = N4_DIR / case.name
    case_out.mkdir(exist_ok=True)

    bias_case_out = BIAS_FIELD_DIR / case.name
    bias_case_out.mkdir(exist_ok=True)

    mask_case_out = N4_MASK_DIR / case.name
    mask_case_out.mkdir(exist_ok=True)

    for modality in N4_MODALITIES:
        geom_path = geom_case_dir / f"{case.name}_{modality}_geom.nii.gz"
        if not geom_path.exists():
            n4_skipped.append({
                "case": case.name,
                "reason": f"{modality} geom dosyası bulunamadı: {geom_path.name}",
            })
            continue

        image, err = read_image(geom_path)
        if image is None:
            n4_skipped.append({"case": case.name, "reason": f"{modality} read error: {err}"})
            continue

        before_array = sitk.GetArrayFromImage(image).astype(np.float32)
        brain_mask_before = before_array > 0
        if brain_mask_before.sum() == 0:
            n4_skipped.append({"case": case.name, "reason": f"{modality}: brain mask boş"})
            continue

        corrected_image, mask_image, bias_field_image = run_n4_correction(image)

        corrected_array = sitk.GetArrayFromImage(corrected_image)
        mask_array = sitk.GetArrayFromImage(mask_image).astype(bool)
        bias_field_array = sitk.GetArrayFromImage(bias_field_image)

        assert corrected_array.shape == before_array.shape, (
            f"{case.name}/{modality}: N4 sonrası shape değişti"
        )

        background_mask = before_array <= 0

        assert np.allclose(corrected_array[background_mask], 0.0, atol=1e-3), (
            f"{case.name}/{modality}: arka plan bias correction sonrası bozuldu"
        )
        assert corrected_array.min() >= -1e-3, (
            f"{case.name}/{modality}: N4 sonrası negatif yoğunluk üretildi"
        )

        brain_bias_values = bias_field_array[mask_array] if mask_array.any() else bias_field_array[brain_mask_before]

        corrected_image.CopyInformation(image)

        out_path = case_out / f"{case.name}_{modality}_n4.nii.gz"
        sitk.WriteImage(corrected_image, str(out_path))

        bias_out_path = bias_case_out / f"{case.name}_{modality}_biasfield.nii.gz"
        sitk.WriteImage(bias_field_image, str(bias_out_path))

        mask_to_save = sitk.Cast(mask_image, sitk.sitkUInt8)
        mask_out_path = mask_case_out / f"{case.name}_{modality}_otsumask.nii.gz"
        sitk.WriteImage(mask_to_save, str(mask_out_path))

        n4_records.append({
            "case": case.name,
            "site": get_site(case.name),
            "modality": modality,
            "before_mean": float(before_array[brain_mask_before].mean()),
            "before_std": float(before_array[brain_mask_before].std()),
            "after_mean": float(corrected_array[brain_mask_before].mean()),
            "after_std": float(corrected_array[brain_mask_before].std()),
            "cv_before": float(before_array[brain_mask_before].std() / (before_array[brain_mask_before].mean() + 1e-8)),
            "cv_after": float(corrected_array[brain_mask_before].std() / (corrected_array[brain_mask_before].mean() + 1e-8)),
            "bias_field_min": float(brain_bias_values.min()),
            "bias_field_max": float(brain_bias_values.max()),
            "bias_field_mean": float(brain_bias_values.mean()),
            "otsu_mask_voxels": int(mask_array.sum()),
        })

        print(
            f"   {case.name}/{modality:<6}"
            f" CV before={n4_records[-1]['cv_before']:.4f}"
            f" CV after={n4_records[-1]['cv_after']:.4f}"
            f" bias[min={n4_records[-1]['bias_field_min']:.3f}"
            f" max={n4_records[-1]['bias_field_max']:.3f}]"
        )

print()
print("=" * 80)
print(f"SKIPPED: {len(n4_skipped)}")
print("=" * 80)
if n4_skipped:
    for s in n4_skipped:
        print(f"  - {s['case']}: {s['reason']}")
else:
    print("  (none)")

n4_df = pd.DataFrame(n4_records)
n4_csv = MANIFEST_DIR / "n4_bias_correction_statistics.csv"
n4_df.to_csv(n4_csv, index=False)

print()
print("=" * 80)
print("SUMMARY")
print("=" * 80)
print(f"Images processed : {len(n4_df)}")
if len(n4_df):
    print()
    print("Coefficient of Variation (intensity homojenliği; N4 sonrası düşmesi beklenir)")
    print(n4_df[["cv_before", "cv_after"]].describe())
    print()
    print("Bias field range (brain)")
    print(n4_df[["bias_field_min", "bias_field_max", "bias_field_mean"]].describe())
print()
print(f"Corrected images -> {N4_DIR}")
print(f"Bias fields      -> {BIAS_FIELD_DIR}")
print(f"Otsu masks       -> {N4_MASK_DIR}")
print(f"Statistics saved -> {n4_csv}")
print("=" * 80)
display(n4_df.head(10))

# ROBUST BRAIN MASK (Otsu + Morphological Closing + Fill Holes)

BRAIN_MASK_DIR = PREPROCESSED_DIR / "brain_masks"
BRAIN_MASK_DIR.mkdir(parents=True, exist_ok=True)

CLOSING_RADIUS_MM = 2      # morfolojik closing yarıçapı (voksel, spacing=1mm izotropik olduğundan mm ile aynı)
FILL_HOLES_FULLY_CONNECTED = False

print("=" * 80)
print("NEUROVISION ROBUST BRAIN MASK")
print("Otsu Thresholding -> Binary Morphological Closing -> Binary Fill Holes")
print(f"Input          : {N4_DIR} (referans modalite: FLAIR, bias-corrected)")
print(f"Closing radius : {CLOSING_RADIUS_MM} voksel")
print("=" * 80)


def build_robust_brain_mask(image):
    """FLAIR (N4 sonrası) üzerinden 3 aşamalı, delik doldurulmuş beyin maskesi üretir.

    1) Otsu: kaba beyin/kafa vs arka plan ayrımı.
    2) Morphological Closing: Otsu'nun bıraktığı küçük boşlukları/kopuklukları
       kapatır (ör. damar/BOS bölgelerinde lokal düşük sinyal nedeniyle
       oluşan delikler, kenarlardaki tırtıklı kopukluklar).
    3) Binary Fill Holes: kapalı sınır içinde kalan tüm iç boşlukları
       (ventriküller dahil) doldurarak tek parça, katı bir beyin hacmi verir.

    N4'ün kendi içindeki ham Otsu maskesinden farklı olarak bu maske
    segmentasyon / FCM gibi sonraki adımlarda "beyin dokusu" tanımı olarak
    kullanılmak üzere tasarlandı.
    """
    otsu_mask = sitk.OtsuThreshold(image, 0, 1, 200)

    closed_mask = sitk.BinaryMorphologicalClosing(
        otsu_mask, [CLOSING_RADIUS_MM] * image.GetDimension(), sitk.sitkBall
    )

    filled_mask = sitk.BinaryFillhole(
        closed_mask, fullyConnected=FILL_HOLES_FULLY_CONNECTED
    )

    return otsu_mask, closed_mask, filled_mask


mask_records = []
mask_skipped = []

cases = find_case_directories(EXTRACTED_DIR)
print(f"Cases found : {len(cases)}")

for case in tqdm(cases, desc="Robust brain mask"):
    flair_n4_path = N4_DIR / case.name / f"{case.name}_FLAIR_n4.nii.gz"
    if not flair_n4_path.exists():
        mask_skipped.append({"case": case.name, "reason": "N4 düzeltilmiş FLAIR bulunamadı"})
        continue

    flair_image, err = read_image(flair_n4_path)
    if flair_image is None:
        mask_skipped.append({"case": case.name, "reason": f"FLAIR read error: {err}"})
        continue

    spacing = flair_image.GetSpacing()
    voxel_volume_mm3 = spacing[0] * spacing[1] * spacing[2]

    otsu_mask, closed_mask, filled_mask = build_robust_brain_mask(flair_image)

    otsu_array = sitk.GetArrayFromImage(otsu_mask).astype(bool)
    closed_array = sitk.GetArrayFromImage(closed_mask).astype(bool)
    filled_array = sitk.GetArrayFromImage(filled_mask).astype(bool)

    # Closing sadece kapatma/birleştirme yapmalı; toplam voksel sayısı
    # Otsu'ya göre azalmamalı (ufak nümerik farklar dışında).
    assert closed_array.sum() >= otsu_array.sum() * 0.98, (
        f"{case.name}: closing sonrası maske beklenmedik şekilde küçüldü"
    )
    # Fill holes sadece iç boşlukları doldurur; toplam voksel closed'a göre
    # artmalı veya eşit kalmalı, asla azalmamalı.
    assert filled_array.sum() >= closed_array.sum(), (
        f"{case.name}: fill holes sonrası maske küçüldü, mantık hatası var"
    )

    final_mask = sitk.Cast(filled_mask, sitk.sitkUInt8)
    final_mask.CopyInformation(flair_image)

    case_out = BRAIN_MASK_DIR / case.name
    case_out.mkdir(exist_ok=True)
    mask_out_path = case_out / f"{case.name}_brain_mask.nii.gz"
    sitk.WriteImage(final_mask, str(mask_out_path))

    holes_filled_voxels = int(filled_array.sum() - closed_array.sum())
    closing_added_voxels = int(closed_array.sum() - otsu_array.sum())

    mask_records.append({
        "case": case.name,
        "site": get_site(case.name),
        "otsu_voxels": int(otsu_array.sum()),
        "closed_voxels": int(closed_array.sum()),
        "filled_voxels": int(filled_array.sum()),
        "closing_added_voxels": closing_added_voxels,
        "holes_filled_voxels": holes_filled_voxels,
        "final_volume_ml": float(filled_array.sum() * voxel_volume_mm3 / 1000),
    })

    print(
        f"   {case.name:<20}"
        f" otsu={int(otsu_array.sum()):>8d}"
        f" closed={int(closed_array.sum()):>8d}"
        f" filled={int(filled_array.sum()):>8d}"
        f" (+closing={closing_added_voxels:>6d}, +holes={holes_filled_voxels:>6d})"
        f" volume={mask_records[-1]['final_volume_ml']:8.1f} ml"
    )

print()
print("=" * 80)
print(f"SKIPPED: {len(mask_skipped)}")
print("=" * 80)
if mask_skipped:
    for s in mask_skipped:
        print(f"  - {s['case']}: {s['reason']}")
else:
    print("  (none)")

mask_df = pd.DataFrame(mask_records)
mask_csv = MANIFEST_DIR / "brain_mask_statistics.csv"
mask_df.to_csv(mask_csv, index=False)

print()
print("=" * 80)
print("SUMMARY")
print("=" * 80)
print(f"Cases processed : {len(mask_df)}")
if len(mask_df):
    print()
    print("Brain volume (ml)")
    print(mask_df["final_volume_ml"].describe())
    print()
    print("Closing / Fill Holes etkisi (voksel)")
    print(mask_df[["closing_added_voxels", "holes_filled_voxels"]].describe())
print()
print(f"Masks saved      -> {BRAIN_MASK_DIR}")
print(f"Statistics saved -> {mask_csv}")
print("=" * 80)
display(mask_df.head(10))

# AUTOMATIC QC: N4 BIAS CORRECTION (Before / After / Difference / Histogram)

N4_QC_N_CASES = 3
N4_QC_MODALITIES = ["FLAIR", "T1", "T2"]

random.seed(42)
qc_case_dirs = sorted([d for d in N4_DIR.iterdir() if d.is_dir()])
qc_selected_cases = random.sample(qc_case_dirs, min(N4_QC_N_CASES, len(qc_case_dirs)))

print("=" * 80)
print("N4 BIAS CORRECTION - AUTOMATIC QC")
print(f"Cases          : {[c.name for c in qc_selected_cases]}")
print(f"Modalities     : {N4_QC_MODALITIES}")
print("=" * 80)

qc_records = []

for case_dir in qc_selected_cases:
    case = case_dir.name

    mask_path = BRAIN_MASK_DIR / case / f"{case}_brain_mask.nii.gz"
    mask_image, err = read_image(mask_path)
    if mask_image is None:
        print(f"  ⚠ SKIPPED {case} - brain mask okunamadı: {err}")
        continue
    mask_array = sitk.GetArrayFromImage(mask_image).astype(bool)

    for modality in N4_QC_MODALITIES:
        before_path = GEOMETRY_DIR / case / f"{case}_{modality}_geom.nii.gz"
        after_path = N4_DIR / case / f"{case}_{modality}_n4.nii.gz"

        if not before_path.exists() or not after_path.exists():
            print(f"  ⚠ SKIPPED {case}/{modality} - before/after dosyası eksik")
            continue

        before_image, err1 = read_image(before_path)
        after_image, err2 = read_image(after_path)
        if before_image is None or after_image is None:
            print(f"  ⚠ SKIPPED {case}/{modality} - read error: {err1 or err2}")
            continue

        before_array = sitk.GetArrayFromImage(before_image).astype(np.float32)
        after_array = sitk.GetArrayFromImage(after_image).astype(np.float32)
        diff_array = after_array - before_array

        if mask_array.shape != before_array.shape:
            print(f"  ⚠ SHAPE MISMATCH {case}/{modality}: mask={mask_array.shape} image={before_array.shape}")
            continue

        mask_sum_per_slice = mask_array.sum(axis=(1, 2))
        slice_idx = int(np.argmax(mask_sum_per_slice))

        before_slice = before_array[slice_idx]
        after_slice = after_array[slice_idx]
        diff_slice = diff_array[slice_idx]
        mask_slice = mask_array[slice_idx]

        diff_abs_max = float(np.abs(diff_slice).max()) if diff_slice.size else 1.0

        fig, ax = plt.subplots(1, 4, figsize=(22, 5))

        ax[0].imshow(before_slice, cmap="gray")
        ax[0].set_title(f"Before (geometry-standardized)")
        ax[0].axis("off")

        ax[1].imshow(after_slice, cmap="gray")
        ax[1].set_title("After (N4 corrected)")
        ax[1].axis("off")

        im = ax[2].imshow(diff_slice, cmap="RdBu_r", vmin=-diff_abs_max, vmax=diff_abs_max)
        ax[2].set_title("Difference (After - Before)")
        ax[2].axis("off")
        plt.colorbar(im, ax=ax[2], fraction=0.046, pad=0.04)

        before_vals = before_array[mask_array]
        after_vals = after_array[mask_array]
        ax[3].hist(before_vals, bins=100, alpha=0.6, label="before", density=True)
        ax[3].hist(after_vals, bins=100, alpha=0.6, label="after", density=True)
        ax[3].set_title("Intensity Histogram (brain mask)")
        ax[3].legend()

        plt.suptitle(f"{case} - {modality}", fontsize=14)
        plt.tight_layout()

        out_path = VERIFY_DIR / f"{case}_{modality}_n4_qc.png"
        plt.savefig(out_path, dpi=150)
        plt.show()

        cv_before = float(before_vals.std() / (before_vals.mean() + 1e-8))
        cv_after = float(after_vals.std() / (after_vals.mean() + 1e-8))

        qc_records.append({
            "case": case,
            "modality": modality,
            "slice_idx": slice_idx,
            "mean_abs_diff": float(np.abs(diff_array[mask_array]).mean()),
            "max_abs_diff": float(np.abs(diff_array[mask_array]).max()),
            "cv_before": cv_before,
            "cv_after": cv_after,
            "qc_image": str(out_path),
        })

        print(f"  ✓ {case}/{modality}: slice={slice_idx} "
              f"mean|Δ|={qc_records[-1]['mean_abs_diff']:.2f} "
              f"CV {cv_before:.4f} -> {cv_after:.4f}  saved -> {out_path.name}")

qc_df = pd.DataFrame(qc_records)
qc_csv = MANIFEST_DIR / "n4_qc_summary.csv"
qc_df.to_csv(qc_csv, index=False)

print()
print("=" * 80)
print("SUMMARY")
print("=" * 80)
print(f"QC panels generated : {len(qc_df)}")
print(f"Panels saved to      : {VERIFY_DIR}")
print(f"Summary saved to     : {qc_csv}")
print("=" * 80)
display(qc_df)